apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "7-days-to-die.fullname" . }}
  labels:
    {{- include "7-days-to-die.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "7-days-to-die.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "7-days-to-die.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: default
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "7-days-to-die.fullname" . }}-env
          ports:
            - name: gameport1
              containerPort: 26900
              protocol: TCP # Default game ports
            - name: gameport2
              containerPort: 26900
              protocol: UDP # Default game ports
            - name: gameport3
              containerPort: 26901
              protocol: udp # Default game ports
            - name: gameport4
              containerPort: 26902
              protocol: udp # Default game ports
            - name: webadmin
              containerPort: 8080
              protocol: tcp   # OPTIONAL - WEBADMIN
            - name: telnet
              containerPort: 8081
              protocol: tcp   # OPTIONAL - TELNET
            - name: webserver
              containerPort: 8082
              protocol: tcp   # OPTIONAL - WEBSERVER https://7dtd.illy.bz/wiki/Server%20fixes
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: world-saves
              mountPath: /home/sdtdserver/.local/share/7DaysToDie
            - name: config
              mountPath: /home/sdtdserver/lgsm/config-lgsm/sdtdserver
            - name: serverfiles
              mountPath: /home/sdtdserver/serverfiles
            - name: logs
              mountPath: /home/sdtdserver/log
            - name: backup
              mountPath: /home/sdtdserver/lgsm/backup
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
            - name: world-saves
              persistentVolumeClaim: 
                name: {{ include "7-days-to-die.fullname" . }}-world-saves
            - name: config
              persistentVolumeClaim: 
                name: {{ include "7-days-to-die.fullname" . }}-config
            - name: serverfiles
              persistentVolumeClaim: 
                name: {{ include "7-days-to-die.fullname" . }}-serverfiles
            - name: logs
              persistentVolumeClaim: 
                name: {{ include "7-days-to-die.fullname" . }}-logs
            - name: backup
              persistentVolumeClaim: 
                name: {{ include "7-days-to-die.fullname" . }}-backup
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
